version: '3.8'

services:
  # 백엔드 서비스
  backend:
    build: ./backend
    container_name: shamstagram-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///shamstagram.db
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend/instance:/app/instance
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 프론트엔드 서비스
  frontend:
    build: ./frontend
    container_name: shamstagram-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:5000/api}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data: